name: Build, Check, Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '21' ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: 'sbt'

      - name: Check Format
        run:
          sbt scalafmtSbtCheck scalafmtCheckAll

      - name: Compile
        run:
          sbt +clean +compile +test:compile

      - name: Test
        run:
          sbt +test
