name: Build, Check, Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Check Format
        run:
          sbt scalafmtSbtCheck scalafmtCheckAll

      - name: Compile
        run:
          sbt +clean +compile +test:compile

      - name: Test
        run:
          sbt +test
